spring:
  application:
    name: schoolmate
  thymeleaf:
    cache: false
  data:
    web:
      pageable:
        #페이지 1부터 시작
        one-indexed-parameters: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-paltform: org.hibernate.dialect.MySQL8Dialect
  # profiles:
  #   include: oauth
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
