spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb
    username: appuser
    password: pj12587963
com:
  example:
    schoolmate:
      upload:
        path: "upload"
