# 공통
spring:
  application:
    name: schoolmate
  profiles:
    include: oauth, secret
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    web:
      pageable:
        one-indexed-parameters: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
server:
  forward-headers-strategy: NATIVE

jwt:
  access-token-expiry: 1800000 # [ms]
  refresh-token-expiry: 604800000 #[ms]

naver:
  book-api:
    url: https://openapi.naver.com/v1/search/book.json
  image-api:
    url: https://openapi.naver.com/v1/search/image.json

app:
  verification:
    code-expiry-minutes: 5

com:
  example:
    schoolmate:
      upload:
        path: upload

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
